from tkinter import *

root = Tk()
root.geometry("400x700")
root.minsize(400,700)
root.maxsize(400,700)
root.title("Welcome To My Phone")
#----------------------------------------------------------------------------------------------------------------------#
root.iconbitmap('0ICO.ico')
#----------------------------------------------------------------------------------------------------------------------#
W = PhotoImage(file="1BG.png")
#----------------------------------------------------------------------------------------------------------------------#
Wallpaper = Label(image=W)
Wallpaper.pack()
#----------------------------------------------------------------------------------------------------------------------#
Nav = PhotoImage(file='2Nav.png')
#----------------------------------------------------------------------------------------------------------------------#
NavBar = Label(image=Nav)
NavBar.place(y=650)
#----------------------------------------------------------------------------------------------------------------------#
A = PhotoImage(file='Amazon.png')
B = PhotoImage(file='BGMI.png')
C = PhotoImage(file='Calcu.png')
D = PhotoImage(file='Calen.png')
E = PhotoImage(file='Cam.png')
F = PhotoImage(file='Cho.png')
G = PhotoImage(file='Clock.png')
H = PhotoImage(file='COC.png')
I = PhotoImage(file='Conta.png')
J = PhotoImage(file='facebook.png')
K = PhotoImage(file='Filp.png')
L = PhotoImage(file='Gall.png')
M = PhotoImage(file='Gamil.png')
N = PhotoImage(file='Google.png')
O = PhotoImage(file='Insta.png')
P = PhotoImage(file='Sanp.png')
Q = PhotoImage(file='Whats.png')
R = PhotoImage(file='YouTube.png')
#----------------------------------------------------------------------------------------------------------------------#
Amazon     = Label(image=A)
BGMI       = Label(image=B)
Calculator = Label(image=C)
Calendar   = Label(image=D)
Camera     = Label(image=E)
Chrome     = Label(image=F)
Clock      = Label(image=G)
Clash      = Label(image=H)
Contacts   = Label(image=I)
FaceBook   = Label(image=J)
Flipkart   = Label(image=K)
Gallery    = Label(image=L)
Gmail      = Label(image=M)
Google     = Label(image=N)
Instagram  = Label(image=O)
Sanpchat   = Label(image=P)
WhatsApp   = Label(image=Q)
YouTube    = Label(image=R)
#----------------------------------------------------------------------------------------------------------------------#
Label(text="Amazon",    font="arial 9 bold").place(x=20,y=90)
Label(text=" B G M I",  font="arial 9 bold").place(x=120,y=90)
Label(text="Calculator",font="arial 9 bold").place(x=220,y=90)
Label(text="Calendar",  font="arial 9 bold").place(x=300,y=90)
Label(text="Camera",    font="arial 9 bold").place(x=20,y=190)
Label(text="Chrome",    font="arial 9 bold").place(x=120,y=190)
Label(text="Clock",     font="arial 9 bold").place(x=220,y=190)
Label(text=" C O C",    font="arial 9 bold").place(x=300,y=190)
Label(text="Contacts",  font="arial 9 bold").place(x=20,y=290)
Label(text="FaceBook",  font="arial 9 bold").place(x=120,y=290)
Label(text="Flipkart",  font="arial 9 bold").place(x=220,y=290)
Label(text="Gallery",   font="arial 9 bold").place(x=300,y=290)
Label(text="Gmail",     font="arial 9 bold").place(x=20,y=390)
Label(text="Google",    font="arial 9 bold").place(x=120,y=390)
Label(text="Instagram", font="arial 9 bold").place(x=220,y=390)
Label(text="Sanpchat",  font="arial 9 bold").place(x=300,y=390)
Label(text="WhatsApp",  font="arial 9 bold").place(x=20,y=490)
Label(text="YouTube",   font="arial 9 bold").place(x=120,y=490)
#----------------------------------------------------------------------------------------------------------------------#
Amazon      .place(x=20,y=30)
BGMI        .place(x=120,y=30)
Calculator  .place(x=220,y=30)
Calendar    .place(x=300,y=30)
Camera      .place(x=20,y=130)
Chrome      .place(x=120,y=130)
Clock       .place(x=220,y=130)
Clash       .place(x=300,y=130)
Contacts    .place(x=20,y=230)
FaceBook    .place(x=120,y=230)
Flipkart    .place(x=220,y=230)
Gallery     .place(x=300,y=230)
Gmail       .place(x=20,y=330)
Google      .place(x=120,y=330)
Instagram   .place(x=220,y=330)
Sanpchat    .place(x=300,y=330)
WhatsApp    .place(x=20,y=430)
YouTube     .place(x=120,y=430)
#----------------------------------------------------------------------------------------------------------------------#
root.mainloop()
