from tkinter import *
root = Tk()
root.geometry("800x800")
root.minsize(800,800)
root.maxsize(800,800)
root.title("Admission Form")
#________________________________________________________________________________________________________#
Label(root,text="Admission From",font="arial 15 bold").grid(row=1,column=3)
Label(root,text="Enter Your Name").grid(row=2,column=1)
Label(root,text="Enter Your Address").grid(row=3,column=1)
Label(root,text="Enter Your Email Address").grid(row=4,column=1)
Label(root,text="Enter Your Phone Number").grid(row=5,column=1)
Label(root,text="Enter Your Education").grid(row=6,column=1)
Label(root,text="Enter Your Collage Name").grid(row=7,column=1)
Entry(root).grid(row=2,column=2)
Entry(root).grid(row=3,column=2)
Entry(root).grid(row=4,column=2)
Entry(root).grid(row=5,column=2)
Entry(root).grid(row=6,column=2)
Entry(root).grid(row=7,column=2)
root.mainloop()
